### ISSUE TITLE
섹션 6회차 CPT23,24 QUIZ (실행컨텍스트, 클로저)

### ISSUE THREAD

**Issue by bishoe01** [bishoe01/JS_DEEP_DIVE_STUDY#22]
#### **실행 컨텍스트란 무엇인가요?**

<details>
<summary>답</summary>

1. 자바스크립트 코드가 실행되는 환경을 추상화한 개념
2. 변수, 함수, 스코프 등 코드 실행에 필요한 정보를 담고 있으며, 코드 실행 순서를 관리합니다.

> 
- 코드를 실행하는데 필요한 환경을 제공하는 객체
- 환경 : 코드 실행에 영향을 주는 조건이나 상태
- 식별자 결정을 더욱 효율적으로 하기 위한 수단 
</details>

-----

#### **렉시컬 환경이란 무엇인가요?** 

<details>
<summary>답</summary>

1. 식별자(변수, 함수)와 값의 바인딩 정보, 상위 스코프 참조를 저장하는 자료구조입니다.
2. 스코프 체이닝을 통해 상위 스코프의 변수에 접근할 수 있도록 합니다.
![alt text](image.png)
</details>

-----

#### **콜 스택이란 무엇인가요?**

<details>
<summary>답</summary>

1. 함수 호출 시 생성되는 실행 컨텍스트를 스택 형태로 관리하는 자료구조입니다. 
2. 함수 호출 순서를 추적하고 현재 실행 중인 함수를 관리합니다.

</details>

-----

#### **스코프 체이닝이란 무엇인가요? 아래 코드에 빗대어서 설명** 
```javascript
const x = 1;

function foo() {
    const y = 2;
    function bar() {
    const z = 3;
    console.log(x + y + z);
    }
    bar();
}
foo();
```
<details>
<summary>답</summary>

현재 실행 중인 실행 컨텍스트의 렉시컬 환경부터 시작하여 상위 렉시컬 환경으로 이동하며 식별자를 검색하는 과정입니다.

</details>

#### 다음 코드의 실행 결과를 예측하고, 식별자 결정과정을 설명 (각 단계별 실행 컨텍스트와 스코프 체인을 활용하여 설명) (식별자 결정 : 코드에서 함수나 변수 값을 결정하는 것)

```javascript
let lamp = false;

function goto2F() {
  let lamp = true;
  function goto3F() {
    let puppy = "choco";
    console.log(lamp); // 1
    console.log(puppy); //2
    console.log(king); //3
  }

  goto3F();
}
goto2F();
```

<details>
<summary>답</summary>

* **실행 결과:** 
1. `true`
2. `"choco"`
3. `ReferenceError: king is not defined`

* **실행 컨텍스트 및 스코프 체인:**
1. 전역 실행 컨텍스트
   - 변수 환경: `{ lamp: false }`
   - 스코프 체인: `null`
2. `goto2F` 함수 실행 컨텍스트
    - 변수 환경: `{ lamp: true }`
    - 스코프 체인: `goto2F 변수 환경 -> 전역 변수 환경`
3. `goto3F` 함수 실행 컨텍스트
    - 변수 환경: `{ puppy: "choco" }`
    - 스코프 체인: `goto3F 변수 환경 -> goto2F 변수 환경 -> 전역 변수 환경`

#변수섀도잉, #식별자결정, #스코프체이닝

</details>

-------

#### 정적 스코프와 동적 스코프 개념을 설명하고, 자바스크립트는 어떠한 스코프를 사용하는지 설명하시오.
<details>
<summary>답변 보기</summary>

- 동적 스코프(lexical scoping): 함수를 어디서 호출했는지에 따라 상위 스코프가 결정되는 스코프입니다. 함수를 어디서 선언했는지에 따라 상위 스코프가 결정됩니다.

- 정적 스코프(dynamic scoping): 함수를 어디서 호출했는지가 아닌, 어디에 선언되었는지에 따라 상위 스코프가 결정되는 스코프입니다.

- 자바스크립트는 정적 스코프를 사용합니다. 함수를 선언한 시점에 상위 스코프가 결정되며, 함수를 어디서 호출했는지와는 관계없이 상위 스코프를 참조합니다.

</details>

------

#### 클로저에 대해 설명하고, 클로저의 사용 목적을 설명하시오.
<details>
<summary>답</summary>

>외부 함수의 변수에 접근할 수 있는 함수를 말한다. (중첩 함수는 이미 생명주기가 끝난 외부 함수의 변수를 참조할 수 있다.)
##### 사용목적
1. 클로저는 함수와 그 함수가 선언될 당시의 렉시컬 환경과의 조합이다.
2. 사용목적 : 상태 유지(stateful) -> 의도치 않게 변경되지 않도록 은닉, 특정함수에게만 변경을 허용하기 위해
</details>

------

#### 자유변수란?
<details>
<summary>답변 보기</summary>

1. 클로저 내부 함수에서 사용되지만, 클로저 함수 내부에서 정의되지 않은 변수를 의미합니다.
2. 클로저는 외부 함수의 변수에 접근할 수 있으며, 이때 외부 함수의 변수를 자유변수라고 합니다.
</details>

------

#### 자바스크립트 함수 객체의 [[Environment]] 내부 슬롯은 무엇을 의미하고, 클로저와 어떤 관련이 있나요?
<details>
<summary>답변 보기</summary>

1. [[Environment]] 내부 슬롯은 함수가 생성될 당시의 렉시컬 환경(Lexical Environment)에 대한 참조를 저장합니다. 
2. 렉시컬 환경은 함수가 정의된 위치의 스코프에 대한 정보를 담고 있으며, 클로저는 이 [[Environment]] 내부 슬롯을 통해 상위 스코프의 변수에 접근할 수 있습니다. 
3. 클로저는 함수와 해당 함수가 생성될 때의 렉시컬 환경의 조합이며, [[Environment]] 내부 슬롯은 클로저의 핵심 동작 원리를 가능하게 하는 중요한 요소입니다.

```bash
inner.[[Environment]] = {
  middleVar: "중간 변수",
  outer: <outer 함수 객체에 대한 참조>,
  ... (기타 내장 함수 및 객체)
}
```
</details>

-----

#### 클로저를 활용하여 구현한 함수입니다. 실행 결과와 동작원리를 설명해주세요 
    
```javascript
function closure() {
  let x = 0;
  function increment() {
    return ++x;
  }
  return increment; //
}

const result = closure();
const result2 = closure();
console.log(result()); //
console.log(result()); //
console.log(result2());
console.log(result2());

```
<details>
<summary>답</summary>
<ul>
<li>1 - 1</li>
<li>2 - 2</li>
<li>3 - 1</li>
<li>4 - 2</li>
</ul>
</details>

**Comment by Yoosun-Chang** [comment]
굿굿
