### ISSUE TITLE
1회차 chapter4~6 퀴즈

### ISSUE THREAD

**Issue by GEONU-MOON** [bishoe01/JS_DEEP_DIVE_STUDY#4]
### Q. [변수 호이스팅이란?]
<details>

<summary>A. [정답]</summary>
[변수 호이스팅(Variable Hoisting)은 자바스크립트에서 변수 선언이 해당 스코프의 최상단으로 끌어올려지는 현상을 말합니다.]
</details>

### Q. [var과 let과 const의 차이는?]
<details>

<summary>A. [정답]</summary>
var: 함수 스코프를 가짐, 재선언&재할당 가능, 호이스팅에 영향을 받음<br/>
let: 블록 스코프를 가짐, 재선언 불가, 재할당 가능<br/>
const 블록 스코프를 가짐, 반드시 선언과 동시에 초기화를 해야 함, 재선언&재할당 불가능
</details>

### Q. [표현식과 문의 차이점은?]
<details>

<summary>A. [정답]</summary>
표현식은 값으로 평가될 수 있는 코드 조각.<br/>
변수, 상수, 리터럴 값, 연산자 등의 조합으로 이루어짐.<br/>
예시: 5, x + 3, 2 * (y - 1), true && false, func()<br/>
<br/>
문은 프로그램을 구성하는 실행 가능한 코드 단위.<br/>
문은 표현식의 조합이며, 표현식을 포함할 수 있음.<br/>
예시: 변수 선언문 (let x = 5;), 할당문 (x = 10;), 조건문 (if (x > 0) { ... }), 반복문 (for (let i = 0; i < 5; i++) { ... }), 함수 선언문 (function add(a, b) { ... }), 표현식 문 (x + 3;)
</details>

### Q. [undefined와 null에 대해 설명하시오]
<details>

<summary>A. [정답]</summary>
undefined: 타입이자 값. 자바스크립트 엔진이 변수를 초기화할 때 사용하는 값으로 변수를 초기화하지 않으면 자동으로 할당됨<br/>
null: 타입이자 값. 변수에 값이 없다는 것을 의도적으로 명시할 때(이전에 참조하던 값을 더 이상 참조하지 않겠다는 뜻 -> 가비지콜렉션에 영향)나 함수가 유효한 값을 반환할 수 없는 경우 반환됨
</details>

### Q. [자바스크립트 원시 타입이란?]
<details>

<summary>A. [정답]</summary>
자바스크립트 원시 타입은 숫자, 문자열, 불리언, null, undefined, 심볼과 같은 기본적인 데이터 타입을 말한다.<br/> 이러한 원시 타입은 불변하며, 메모리에 고정된 크기로 저장된다.<br/>원시 타입은 값 그 자체로 존재하며, 다른 변수에 할당될 때 값이 복사된다.
</details>

### Q. [자바스크립트 객체 타입이란?]
<details>

<summary>A. [정답]</summary>
자바스크립트에서 객체 타입은 값의 종류를 나타내는 것.<br/>객체는 여러 속성과 메서드를 포함할 수 있는 복합적인 데이터 유형이다.<br/>  객체는 중괄호 {}를 사용하여 생성되며, 속성과 메서드는 객체 내에 키-값 쌍으로 정의된다.<br/> 

자바스크립트에서 기본적으로 제공되는 객체 타입에는 다음과 같은 것들이 있다:<br/> 

Object: 모든 객체의 기본이 되는 객체 타입입니다.<br/> 
Array: 순서가 있는 값의 집합을 나타내는 객체 타입입니다.<br/> 
String: 문자열을 나타내는 객체 타입입니다.<br/> 
Number: 숫자를 나타내는 객체 타입입니다.<br/> 
Boolean: 논리적인 참과 거짓을 나타내는 객체 타입입니다.<br/> 
Function: 함수를 나타내는 객체 타입입니다.<br/> 
이 외에도 자바스크립트에서는 다양한 내장 객체 타입을 제공하며, 사용자 정의 객체 타입을 생성할 수도 있습니다. 객체 타입은 자바스크립트의 핵심적인 개념 중 하나이며, 객체를 다루는 데 필수적입니다.<br/> 
</details>

### Q.동적타입이란? / js가 왜 동적타입인지?
<details>
<summary>정답</summary>
프로그래밍 언어에서 변수의 데이터 타입이 런타임(runtime)에 결정되는 것을 의미한다.<br/> 이는 변수의 값이 할당될 때 그 값의 데이터 타입에 따라 변수의 타입이 자동으로 결정된다는 것을 의미한다.<br/>
자바스크립트는 동적타입 언어라서 변수의 타입을 할당 시점에 결정하기 때문이다.
</details>

### Q. 이 코드의 결과는?
 ```js
a=100;
b=200;
console.log(a);
console.log(b);
var a = 10;
let b = 20;
```
( a, b 출력 결과 )& 이유는 ?
<details>
<summary>정답</summary>
a =100
b =Uncaught ReferenceError: Cannot access 'b' before initialization
</details>

**Comment by Yoosun-Chang** [comment]
Q. [변수 호이스팅이란?]
A. 변수 선언문이 코드의 선두로 끌어 올려진 것처럼 동작하는 것

Q. [var과 let과 const의 차이는?]
A. var : 선언과 초기화가 함께 이루어진다.
let, const: 선언과 초기화가 분리되어 있고, const는 선언과 동시에 반드시 초기화되어야 한다.

Q. [표현식과 문의 차이점은?]
A. 표현식은 값으로 표현이 되어야하고 문은 값으로 표현이 안되어도 된다.

Q. [undefined와 null에 대해 설명하시오]
A. undefined는 변수 선언 후, 아무것도 할당하지 않은 변수를 참조할 때 반환되는 값이다.
null은 값이 없다는 것을 명시적으로 나타내고자 할 때 할당하는 값이다.

Q. [자바스크립트 원시 타입이란?]
A. 메모리 공간에 실제 값이 저장된다.

Q. [자바스크립트 객체 타입이란?]
A. 여러 데이터를 하나의 단위로 묶어서 관리할 수 있도록 하는 데이터 타입

Q.동적타입이란? / js가 왜 동적타입인지?
변수를 선언할 때 타입을 선언하지 않는 언어
js는 타입 대신 var, let, const로 변수를 선언한다. 

Q. 이 코드의 결과는?
```js
a=100;
b=200;
console.log(a);
console.log(b);
var a = 10;
let b = 20;
```
( a, b 출력 결과 )& 이유는 ?
100
200

변수가 선언이 되면 호이스팅에 의해 해당 변수가  최상단으로 올라가게되어 변수가 선언이 되고, 값이 할당된다. 그 후 100, 200으로 재할당을 해주었으므로 100, 200이 출력된다.

**Comment by bishoe01** [comment]
1. Q. [변수 호이스팅이란?] 
->  변수 선언문이 코드의 선두로 끌어올려진 것처럼 동작하는 현상  var과 함수들이 호이스팅되어 동작함 


Q. [var과 let과 const의 차이는?]
- var은 함수레벨 스코프
- let과 const는 블록레벨 스코프 
- let,var 은 값 재할당/재선언 가능
- const는 재할당/재선언 불가능
- const는 그래서 선언해줄때 할당도 같이 해줘야한다 

Q. [표현식과 문의 차이점은?]
A. 
- 표현식 : 값으로 평가될 수 있는 문(statement)
- 문 : 프로그램을 구성하는 기본 단위이자 최소 실행 단위
- -> 문은 여러 토큰으로 구성됨 ( 토큰 : 키워드 , 식별자 , 연산자 ,리터럴 등 )

Q. [undefined와 null에 대해 설명하시오]
A. 
null은  값이 없음을 표현할 때 사용되는 값
undefined는 값이 할당되지 않은 상태를 표현할 때 사용 
없음과 할당 안함의 차이고 ,  c언어에서 쓰레기값이 들어가는 것 처럼  js에서는 그 대신에 undefined라는 값을 할당해주는 것 

```js
undefined/1  //NaN
null/1      // 0
```

Q. [자바스크립트 원시 타입이란?]
A. 숫자 , 문자열, 불리언, undefined , null , Symbol

Q. [자바스크립트 객체 타입이란?]
A. Object 타입인데, JS에서는 원시 타입을 제외한 모든 값이 객체로 처리된다고 한다. 

Q.동적타입이란? / js가 왜 동적타입인지?
- 자바스크립트는 변수가 선언할때가 아니라, 할당할 때 타입추론을 하는 구조라서, 실행될 때 변수의 타입이 정해지게 되는 구조다. 그래서 타입도 계속해서 동적으로 변경할 수 있어서 편하게 사용할 수 있다는 장점이 있지만, 의도하지 않은 방식대로 코드가 진행될 수도 있다는 위험도 존재한다. 
Q. 이 코드의 결과는?
a=100;
b=200;
console.log(a);
console.log(b);
var a = 10;
let b = 20;
( a, b 출력 결과 )& 이유는 ?
a는 100 이고 
b는 참조에러가 뜰것

a는 var이라서 호이스팅으로 선언이 먼저 되어서 
var a ; 
가 먼저 실행된 상태로 undefined인 a에 100을 할당한 것이다. 그리고 맨밑에서 a = 10 이 마지막으로 실행될거라서 맨 마지막에 한번더 console.log(a)를 찍으면 아마 10이 나올 것이다.
b는 let/const라서 var과 다르게 선언과 초기화가 다른 시점에 일어나기 때문에 TDZ- Temporary Dead Zone 구간에 있기때문에 참조에러가 발생한다고 한다. 

<img width="684" alt="스크린샷 2024-05-03 오후 2 20 06" src="https://github.com/bishoe01/JS_DEEP_DIVE_STUDY/assets/50870343/b7b0f5a0-2974-4733-9dea-fd34aa6db309">

<img width="532" alt="스크린샷 2024-05-03 오후 2 23 05" src="https://github.com/bishoe01/JS_DEEP_DIVE_STUDY/assets/50870343/b6b6e1e0-3266-413d-92af-5764ab82c0c4">

**Comment by hyeong1** [comment]
Q. 변수 호이스팅
- 선언문을 코드의 선두로 끌어 올려진 것처럼 동작하는 것. 런타임 이전에 모든 선언문을 소스코드에서 찾아내 먼저 실행하는 것.

Q. var, let, const 차이
- var: var 키워드로 선언한 변수는 선언 단계와 초기화 단계가 동시에 진행된다. var 키워드로 선언한 변수는 값을 할당하지 않아도 undefined라는 값을 갖는다.
- let: 
- const: const 키워드로 선언한 변수는 값을 수정할 수 없다.

Q. 표현식과 문의 차이
- 표현식은 값으로 평가될 수 있는 문이고 문은 프로그램을 구성하는 기본 단위이자 최소 실행 단위이다. 

Q. undefined, null
- undefined는 var 키워드로 선언한 변수를 자바스크립트 엔진이 초기화할 때 사용하는 값이다. 변수에 값이 없다는 것을 명시하고 싶을 때 null을 사용한다. 

Q. 자바스크립트 원시 타입
- 숫자, 문자열, 불리언, undefined, null, 심벌
- 값을 수정할 수 없다

Q. 자바스크립트 객체 타입
- 객체, 함수, 배열 등

Q. 동적 타입? / js가 왜 동적타입인지
- 값이 할당될 때 값의 타입을 보고 변수의 데이터 타입이 결정되는 것이 동적 타입이다. js에서는 변수의 데이터 타입을 명시하지 않고 값이 할당될 때 타입이 동적으로 결정되며 언제든지 타입을 변경할 수 있기 때문에 js는 동적 타입 언어이다.

Q. 이 코드의 결과
a=100;
b=200;
console.log(a);
console.log(b);
var a = 10;
let b = 20;

```
100
200
```
변수 a와 b의 선언은 런타임 전에 실행된다. 런타임 중에 a = 10, b = 20 이 코드보다 a = 100, b= 200이 먼저 실행되고 출력되기 때문에 a는 100, b는 200이 출력된다.
