### ISSUE TITLE
2회차 섹션 퀴즈 Cpt07 -Cpt11

### ISSUE THREAD

**Issue by bishoe01** [bishoe01/JS_DEEP_DIVE_STUDY#6]
### 1. Q : 각 줄마다 출력값을 작성해주세요
```js
let num = 5;
console.log(++num);  //  1번
console.log(num); //  2번
console.log(num++); //  3번
console.log(num); //  4번 
let str = '5';
console.log(++str + true); //  5번
console.log(0===-0); // 6번 
console.log(0==-0); // 7번
console.log(!null); // true
console.log(!undefined); // true
```

------

### 2-1 Q: 그렇다면 다음 코드의 출력 결과를 예측하고, 이유를 설명하시오.
```js
console.log(5 == '5');  // 
console.log(5 === '5');  //
```

#### 3번 문제 코드 예시
```let x=  10;
let result = x % 2 ? '홀수' : '짝수';
let result2 = if(x % 2) { return '홀수'; } else { return '짝수'; }
```

------

### 4. Q: 다음 코드의 실행 결과는 ? 고칠곳이 있다면 고치고, 이유를 설명해주세요.
```js
let poketmon = '피카츄';
let master;
switch (poketmon) {
    case '파이리':
        master = '웅이';
    case '꼬부기':
        master = '이슬이';
    case '피카츄':
        master = '지우';
    default:
        master = '로켓단';
}
console.log(master); //
```

--------

### 5. Q: 아래 코드에서 각 줄의 출력값과 그 이유를 설명해주세요
```js
let x ;
console.log(String(x));
console.log(x.toString()); 
```

-----

### 6. Q : 아래 코드에서 각 줄의 출력값과 그 이유를 설명해주세요

```js
'CAT' && 'DOG'; // 
'CAT' || 'DOG'; // 

false && 'DOG'; //
true || 'DOG'; //

```

### 7. Q : 다음은 단축 평가로 에러를 방지하는 코드이다.  let value = elem && elem.value; 이외에 다른 방법으로 에러를 방지할 수 있는 코드를 작성해주세요.

```js
let elem = null;
let value = elem.value; 

// 단축 평가로 에러 방지
let elem = null;
let value = elem && elem.value;  //  <- 해당 부분
console.log(value);
```

------

**Comment by hyeong1** [comment]
#### 1
1번: 6
2번: 6
3번: 6
4번: 7
5번: 7
6번: false
7번: true
8번: true
9번: true
#### 2
동등 비교 연산자는 비교하기 전 암묵적 타입 변환을 통해 타입을 일치시키고 값이 같은지 비교한다. 비교 일치 연산자는 암묵적 타입 변환을 하지 않고 값을 비교한다.
#### 2-1
true, false
첫 번째 코드는 암묵적 타입 변환 후 값을 비교하므로 true, 두 번째 코드는 타입과 값 모두 비교하므로 false이다.
#### 3-1
T
#### 3-2
F
#### 4
결과: 로켓단
case 문에 break 문이 없기 때문에 case '피카츄' 문에서 master 값이 '지우'가 된다음에 default 문에 의해 master가 '로켓단'으로 갱신된다. (폴스루 발생)
#### 5
string
string
두 방법 모두 문자열 명시적 타입 변환 방법이므로 결과로 string가 출력된다.
#### 6
'DOG' // 논리 곱 연산자는 논리 연산 결과를 결정하는 두 번째 피연산자를 반환하므로 결과는 'DOG'이다.
'CAT' //  논리 합 연산자는 논리 연산의 결과를 결정하는 첫 번째 피연산자를 반환하므로 결과는 'CAT'이다.

// 아래 두 코드는 논리 연산 결과가 먼저 결정되었기 때문에 결과가 각각 false, true가 된다.
false
true
#### 7
```javascript
let value;
if (elem)
  value = elem.value;
```
#### 8
원시 값은 메모리에 값이 저장되고, 객체에는 참조 주소가 저장된다.

**Comment by Yoosun-Chang** [comment]
### 1. Q : 각 줄마다 출력값을 작성해주세요
```js
let num = 5;
console.log(++num);  //  1번
console.log(num); //  2번
console.log(num++); //  3번
console.log(num); //  4번 
let str = '5';
console.log(++str + true); //  5번
console.log(0===-0); // 6번 
console.log(0==-0); // 7번
console.log(!null); // true
console.log(!undefined); // true
```

1번 6
2번 6
4번 6
4번 7

5번 7
6번 true
7번 ture

------

### 2. Q: 동등 비교 연산자와 비교 일치 연산자의 차이점을 설명하시오.

동등 비교 연산자는 느슨한 비교, 일치 비교 연산자는 엄격한 비교를 함.
   - 동등 비교 == : 값만 같은지 비교
   - 일치 비교 === : 값과 타입까지 같은지 비교
   - 부동등 비교 != : 값만 다른지 비교
   - 불일치 비교 !== : 값과 타입까지 다른지 비교

### 2-1 Q: 그렇다면 다음 코드의 출력 결과를 예측하고, 이유를 설명하시오.
```js
console.log(5 == '5');  // 
console.log(5 === '5');  //
```
true
false

위는 동등 비교 연산자이고 아래는 일치 비교 연산자이다. 따라서 위에는 값만 같은지 확인하고,
아래는 값과 타입까지 같은지 비교한다.

#### 3-1 Q: if_else 문은 삼항 조건 연산자로 대체할 수 있다. (T/F) 
T

#### 3-2 Q: 삼항 조건 연산자 표현식은 if_else문으로 대체할 수 없다.(T/F)
F

#### 3번 문제 코드 예시
```let x=  10;
let result = x % 2 ? '홀수' : '짝수';
let result2 = if(x % 2) { return '홀수'; } else { return '짝수'; }
```

------

### 4. Q: 다음 코드의 실행 결과는 ? 고칠곳이 있다면 고치고, 이유를 설명해주세요.
```js
let poketmon = '피카츄';
let master;
switch (poketmon) {
    case '파이리':
        master = '웅이';
    case '꼬부기':
        master = '이슬이';
    case '피카츄':
        master = '지우';
    default:
        master = '로켓단';
}
console.log(master); //
```

break가 없으면 풀스루가 일어날 수 있기 떄문에 break를 해준다.

--------


### 5. Q: 아래 코드에서 각 줄의 출력값과 그 이유를 설명해주세요
```js
let x ;
console.log(String(x));
console.log(x.toString()); 
```

undefined
typeError

선언만 하고 값을 할당하지 않았다.
undefined는 값이 아니기 때문에 문자열로 바꿀수 없다.
-----

### 6. Q : 아래 코드에서 각 줄의 출력값과 그 이유를 설명해주세요

```js
'CAT' && 'DOG'; // 
'CAT' || 'DOG'; // 

false && 'DOG'; //
true || 'DOG'; //

```

DOG - 논리 연산의 결과를 결정하는 두 번째 피연산자를 반환
CAT- 논리 연산의 결과를 결정하는 첫 번째 피연산자를 반환
false 
true


### 7. Q : 다음은 단축 평가로 에러를 방지하는 코드이다.  let value = elem && elem.value; 이외에 다른 방법으로 에러를 방지할 수 있는 코드를 작성해주세요.

```js
let elem = null;
let value = elem.value; 

// 단축 평가로 에러 방지
let elem = null;
let value = elem && elem.value;  //  <- 해당 부분
console.log(value);
```

```
let elem = null;
let value = elem?.value; 
console.log(value);
```
------

### 8 Q: 자바스크립트에서 변수에 원시 값과 객체를 할당할 때 각각 메모리에 저장되는 값은 무엇인가요?

실제 값, 참조 값

**Comment by GEONU-MOON** [comment]
1.
```javascript
let num = 5;
console.log(++num); // 6
console.log(num); // 6
console.log(num++); // 6
console.log(num); // 7
let str = "5";
console.log(++str + true); // 6true
console.log(0 === -0); // true
console.log(0 == -0); // true
console.log(!null); // true
console.log(!undefined); //true
```
---
2. 동등연산자(==)는 피연산자들의 값만 비교. 반면에 일치연산자(===)는 피연산자들의 값과 타입을 모두 비교.
2-1. True / false(타입이 다름)
---
3.
3-1) T
3-2) F
---
4. 로켓단 / breakl문으로 빠져 나가면 지우가 됨.
---
5. undefined : 값 할당이 없어서 undefined 가 할당되어있는데, 문자열로 출력함.
---
6. 'CAT' && 'DOG';는 'CAT'이 참이고 'DOG'도 참이므로 둘 다 참인 조건이 됨. 따라서 마지막으로 평가된 값인 'DOG'가 반환. CAT' || 'DOG';는 'CAT'이 참이기 때문에 바로 'CAT'이 반환. false && 'DOG';는 첫 번째 값이 거짓이기 때문에 뒤의 값은 평가 안함. 따라서 평가 결과는 false가 반환. true || 'DOG';는 첫 번째 값이 참이기 때문에 뒤의 값은 평가 안함. 따라서 평가 결과는 true가 반환.
---
7.
```javascript
let elem = null;
let value = elem?.value;
```
---
8. 변수에 원시 값이 할당되면 값 자체가 변수에 저장되고, 변수에 객체가 할당되면 객체의 참조가 변수에 저장됨.
